version: '3'

networks:
  backend:
  frontend:

services:
  mongo:
    image: mongo:latest
    ports:
    - 27017:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
    - backend

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=root
    - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    networks:
    - backend

  mailhog:
    image: mailhog/mailhog
    ports: 
    - 1025:1025 # smtp server
    - 8025:8025 # web ui
    networks:
    - backend